### ISSUE TITLE
DCOS-CLI is not getting installed. 

### ISSUE THREAD

**Issue by neethugeorge** [microservices-today/IaC-dcos#89]
Following is the error message:

`Installing DCOS CLI from PyPI...

New python executable in /home/centos/dcos-cli/bin/python
Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/centos/dcos-cli/bin/dcos", line 7, in <module>
    from dcoscli.main import main
  File "/home/centos/dcos-cli/lib/python2.7/site-packages/dcoscli/main.py", line 7, in <module>
    from dcos import config, constants, emitting, errors, http, subcommand, util
  File "/home/centos/dcos-cli/lib/python2.7/site-packages/dcos/config.py", line 10, in <module>
    from dcos import constants, jsonitem, subcommand, util
  File "/home/centos/dcos-cli/lib/python2.7/site-packages/dcos/subcommand.py", line 12, in <module>
    from subprocess import PIPE
ImportError: cannot import name PIPE`

**Comment by neethugeorge** [comment]
Issue resolved by #90
